# Site settings
title: RLMS codebooks as html and in google translated
email: markuskainu@gmail.com
description: "Another site with data analysis"
baseurl: ""
url: "http://muuankarski.github.io/csv-codebook"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
higlighter: rouge
