# Site settings
title: Interactive codebooks for some datasets
email: markuskainu@gmail.com
description: "Another site with data analysis"
baseurl: "http://muuankarski.github.io/csv-codebook"
url: "http://muuankarski.github.io/csv-codebook"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
higlighter: rouge
